# This is a basic workflow that is manually triggered

name: Build MunkiReport-Python2 Package

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

jobs:
  buildpy2pkg:
    runs-on: macos-11

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Get version number
      id: version
      run: echo "::set-output name=version::$( grep '"version"' build-info.json | cut -d\" -f4 )"
    - name: Run build script
      run: ./build-munkireport-python.sh
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        name: MunkiReport-Python2 v${{ steps.version.outputs.version }}
        tag_name: v${{ steps.version.outputs.version }}
        files: build/MunkiReportPython2-*.pkg
